[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 100
target-version = ["py37"]

[tool.isort]
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "quart, tests"
known_third_party = "_pytest, aiofiles, blinker, dotenv, flask, hypercorn, hypothesis, py, jinja2, pytest, werkzeug"
line_length = 100
multi_line_output = 3
no_lines_before = "LOCALFOLDER"
order_by_type = false
reverse_relative = true

[tool.mypy]
allow_redefinition = true
disallow_subclassing_any = true
disallow_untyped_defs = true
strict_equality = true
strict_optional = false
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module =["aiofiles.*", "blinker.*", "dotenv.*", "hypothesis.*", "py.*", "_pytest.*", "pytest.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--no-cov-on-fail --showlocals --strict"
testpaths = ["tests"]
